spring.application.name=acesso-api

spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:acesso_db
spring.datasource.username=sa
spring.datasource.password=sa
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
